[sidebar]
compact = false
emoji = "ğŸ¥"
subtitle = "æ— å›½å¢ƒç”Ÿæ´»æ–¹å¼æ”»ç•¥åˆ†äº«ï¼Œæ¸¯ç¾è‚¡è´¦æˆ·å¼€æˆ·ç¦åˆ©ã€ç¦»å²¸é“¶è¡Œè´¦æˆ·å¼€ç«‹ï¼Œç§»æ°‘ã€å…¨çƒèµ„äº§é…ç½®."

[sidebar.avatar]
enabled = true
local = true
src = "img/getheadimg.jpeg"

[article]
math = false
readingTime = true

[widgets]
homepage = [
    {type = "search"},
    {type = "coupons"}, # å°†ä¼˜æƒ åˆ¸ç§»åˆ°æœç´¢æ¡†ä¸‹é¢
    {type = "archives"},
    {type = "categories"},
    {type = "tag-cloud"}
]

page = [
    {type = "toc"}
]

# æ–°å¢è‡ªå®šä¹‰æ ·å¼è®¾ç½®
[custom_css]
enable = true
file = "scss/custom.scss"
